ID = "ID"
PRODUCT_NAME = "Product Name"
PRICE = "Price"
QUANTITY = "Quantity"
WEIGHT = "Weight"
DATE = "Date"
PLACE = "Place"
CATEGORIES = "Categories"

PRODUCT_NAME_TEXT = "Product Name:"
PRICE_TEXT = "Price:"
QUANTITY_TEXT = "Quantity:"
WEIGHT_TEXT = "Weight:"
PURCHASE_DATE_TEXT = "Purchase Date:"
PURCHASE_PLACE_TEXT = "Purchase Place:"
CATEGORIES_TEXT = "Categories:"
TO = "to"

APPLY_BUTTON_TEXT = "Apply"
SHOW_ALL_BUTTON_TEXT = "Show All"
ADD_EDIT_BUTTON_TEXT = "Add/Edit"
DELETE_BUTTON_TEXT = "Delete"
SUBMIT_BUTTON_TEXT = "Submit"
CLOSE_BUTTON_TEXT = "Close"