ID = "ID"
PRODUCT_NAME = "Наименование товара"
PRICE = "Цена"
QUANTITY = "Количество"
WEIGHT = "Вес"
DATE = "Дата"
PLACE = "Место"
CATEGORIES = "Категории"

PRODUCT_NAME_TEXT = "Наименование товара:"
PRICE_TEXT = "Цена:"
QUANTITY_TEXT = "Количество:"
WEIGHT_TEXT = "Вес:"
PURCHASE_DATE_TEXT = "Дата покупки:"
PURCHASE_PLACE_TEXT = "Место покупки:"
CATEGORIES_TEXT = "Категории:"
TO = "до"

APPLY_BUTTON_TEXT = "Применить"
SHOW_ALL_BUTTON_TEXT = "Показать все"
ADD_EDIT_BUTTON_TEXT = "Добавить/Изменить"
DELETE_BUTTON_TEXT = "Удалить"
SUBMIT_BUTTON_TEXT = "Отправить"
CLOSE_BUTTON_TEXT = "Закрыть"
