ID = "ID"
PRODUCT_NAME = "Nombre del Producto"
PRICE = "Precio"
QUANTITY = "Cantidad"
WEIGHT = "Peso"
DATE = "Fecha"
PLACE = "Lugar"
CATEGORIES = "Categorías"

PRODUCT_NAME_TEXT = "Nombre del Producto:"
PRICE_TEXT = "Precio:"
QUANTITY_TEXT = "Cantidad:"
WEIGHT_TEXT = "Peso:"
PURCHASE_DATE_TEXT = "Fecha de Compra:"
PURCHASE_PLACE_TEXT = "Lugar de Compra:"
CATEGORIES_TEXT = "Categorías:"
TO = "a"

APPLY_BUTTON_TEXT = "Aplicar"
SHOW_ALL_BUTTON_TEXT = "Mostrar Todos"
ADD_EDIT_BUTTON_TEXT = "Agregar/Editar"
DELETE_BUTTON_TEXT = "Borrar"
SUBMIT_BUTTON_TEXT = "Enviar"
CLOSE_BUTTON_TEXT = "Cerrar"
